name: Yokode CI/CD All-in-One

on:
  push:
    branches: ["main"]

jobs:
  infrastructure-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: unduh kode repository
        uses: actions/checkout@v4

      - name: setup Terrafor,=m
        uses: hashicorp/setup-terraform@v3
 
      - name: validasi naskah terraform
        working-directory: ./terraform
        run: |
          terraform init -backend=false
          terraform validate

      - name: validate naskah ansible
        working-directory: ./ansible
        run: ansible-playbook playbook.yaml --syntax-check

      - name: rakit docker image yokode
        run: docker build -t yokode-app:v1 .

      - name: buat kluster kubernetes (KinD)
        uses: helm/kind-action@v1.9.0

      - name: suntikan image ke dalam kluster
        run: kind load docker-image yokode-app:v1 --name chart-testing

      - name: Deploy ke Kubernetes & Uji Koneksi
        run: |
          # 1. Langsung deploy Database (tanpa membuat secret)
          kubectl apply -f k8s/mysql.yaml
          
          # 2. Deploy Aplikasi Laravel
          kubectl apply -f k8s/deployment.yaml

          kubectl wait --for=condition=ready pod -l app=mysql --timeout=120s
          
          # 3. Tunggu aplikasi hidup maksimal 60 detik
          kubectl wait --for=condition=ready pod -l app=yokode --timeout=60s

          kubectl exec deploy/yokode-deployment -- php artisan migrate --force
          
          # 4. Cetak bukti status dan IP
          kubectl get pods -o wide
          kubectl get svc
          
          # 5. Uji koneksi web
          kubectl port-forward svc/yokode-service 8080:80 &
          sleep 5
          curl -I http://localhost:8080
